name: Deploy Dragonball Prod

on:
  push:
    branches:
      - main
 
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: '${{ github.repository }}'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    environment: PROD
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: '${{ env.REGISTRY }}'
          username: tamgoldefy
          password: '${{ secrets.GITHUB_TOKEN }}'

      - name: 'Extract metadata (tags, labels) for FE'
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}'

      - name: Build and push Docker image FE
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}'
          labels: '${{ steps.meta.outputs.labels }}'
      
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
            ARGS: "-rlgoDzvc -i --delete"
            SOURCE: "./docker-compose.yml"
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
            REMOTE_USER: ${{ secrets.REMOTE_USER }}
            TARGET: ${{ secrets.REMOTE_DIR }}/FE/

      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: '${{ secrets.REMOTE_HOST }}'
          username: '${{ secrets.REMOTE_USER }}'
          key:  '${{secrets.SSH_KEY}}'
          script: |
            docker system prune -f
            docker image prune -f -a
            sed -i -e "s/tagVersion/${{ github.sha }}/g" ${{ secrets.REMOTE_DIR }}/FE/docker-compose.yml
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://${{ env.REGISTRY }} -u publisher --password-stdin
            docker-compose -f ${{ secrets.REMOTE_DIR }}/FE/docker-compose.yml pull
            docker-compose -f ${{ secrets.REMOTE_DIR }}/FE/docker-compose.yml down
            docker-compose -f ${{ secrets.REMOTE_DIR }}/FE/docker-compose.yml up -d
