name: Deploy Dragonball Dev

# on:
#   push:
#     branches:
#       - devops/dev-ecs

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: '${{ github.repository }}'
  REGION: ap-southeast-1

jobs:
  - name: Checkout repo
    uses: actions/checkout@v3

  - name: Configure AWS credentials
    uses: aws-actions/configure-aws-credentials@v2 # More information on this action can be found below in the 'AWS Credentials' section
    with:
      role-to-assume: arn:aws:iam::252947678149:role/my-github-actions-role
      aws-region: $REGION
        
  // - name: Login to Amazon ECR
  //   id: login-ecr
  //   uses: aws-actions/amazon-ecr-login@v1
  //   with:
  //     mask-password: 'true'

  // - name: Build, tag, and push docker image to Amazon ECR
  //   env:
  //     REGISTRY: ${{ steps.login-ecr.outputs.registry }}
  //     REPOSITORY: my-ecr-repo
  //     IMAGE_TAG: ${{ github.sha }}
  //   run: |
  //     docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
  //     docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
